### ISSUE TITLE
Too many colors?

### ISSUE THREAD

**Issue by stevenxie** [stevenxie/resume#1]
Shoud I only have one highlight color, instead of three accent colors?

<img width="347" alt="image" src="https://user-images.githubusercontent.com/1376678/48228716-fd95d780-e373-11e8-8a59-62e75806b370.png">

**Comment by stevenxie** [comment]
Speculation was validated:

<img width="565" alt="image" src="https://user-images.githubusercontent.com/1376678/48229320-c3c5d080-e375-11e8-9f42-f1f1da74004a.png">

**Comment by SurienDG** [comment]
Yea, agree with Patrick.  You probably shouldn't have too many colours makes it hard to know what's important.
